
## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.2
notifications:
  email: false
git:
  depth: 99999999
env:
# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)

## uncomment and modify the following lines to manually install system packages
#addons:
script:
  - echo "No tests, we have the utmost confidence in ourselves :P"

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd())); Pkg.pkg"add Documenter Conda AbstractPlotting#master GLMakie#master StatsMakie#master"'
        - julia --project docs/make.jl
      after_success: skip
